import type { Metadata } from "next";
import "./globals.css";
import { ClientWrapper } from "@/lib/clientWrapper";

export const metadata: Metadata = {
  title: "Overlang AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
